/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ChatsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FinalUsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GenesissSearch": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "GenesissSearchAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GenesissSearchBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenesissSearchPublicBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenesissSearchSessionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TeamsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
