/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CanvasChatsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ChatsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FinalUsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GenesissAgents": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "GenesissAgentsAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GenesissAgentsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenesissAgentsPublicBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenesissAgentsSessionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "TeamsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WorkflowsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
